# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('capacidad', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(max_length=200)),
                ('horario_disponible', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha solicitud')),
                ('hora_inicio', models.DateTimeField(verbose_name='hora de inicio')),
                ('hora_termino', models.DateTimeField(verbose_name='hora de termino')),
                ('cantidad_personas', models.IntegerField(default=0)),
                ('insumos', models.ManyToManyField(to='reserva.Insumo')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=20)),
                ('passw', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.Usuario'),
        ),
    ]
